language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
        packages:
            - g++-7
            - clang-5.0

compiler:
    - gcc
    - clang

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make && make test
