site_name: Nik
pages:
    - Welcome: index.md
    - Strings:
        - Overview: strings/overview.md
        - class string:
            - capitalize: strings/string/member_funcs/capitalize.md
            - center: strings/string/member_funcs/center.md
            - count : strings/string/member_funcs/count.md
            - split : strings/string/member_funcs/split.md

theme: material
markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
